version: "3"

tasks:

  lint:go:
    desc: Run Go linters
    cmds:
      - go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
      - cmd: fieldalignment -test=false -fix=true $(PWD)/...
        ignore_error: true
      - docker run --rm -v ${PWD}/:/app -w /app golangci/golangci-lint:v1.55-alpine golangci-lint run -v --fix --timeout=420s -c golangci.yml
